version: "2.3"
services:
  Lynx_BOT:
    cpus: 4
    mem_limit: "23g"
    working_dir: /lynx_bot
    image: lynx-chess/lynx-bot
    build:
      context: .
      target: lynx-bot
    env_file:
      - .env
    volumes:
      - ./lynx_bot-config.yml:/lynx_bot/configtmp.yml
      - ./lichess-bot-logs:/lynx_bot/log
      - ./lynx-logs:/lynx/logs
    command:
      - sh
      - -c
      - |
        sed "s/LICHESS_API_TOKEN/$LICHESS_API_TOKEN/" configtmp.yml > config.yml
        . .venv/bin/activate
        python3 lichess-bot.py
