name: On lynx-bot image
on:
  registry_package:
    types: [published]

jobs:
  on-lynx-bot-image:
    name: On published image
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@v2

      - name: 'On ${{ github.event.name }}'
        run: |
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.registry_package.package_type ${{ github.event.registry_package.package_type }}"
          echo "github.event.registry_package.name: ${{ github.event.registry_package.name }}"
          echo "github.event.registry_package.namespace: ${{ github.event.registry_package.namespace }}"
          echo "github.event.registry_package.package_version.container_metadata.tag.name: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
          echo "github.event.registry_package.package_version.package_url ${{ github.event.registry_package.package_version.package_url }}"

          echo "github.event.registry_package.package_version.container_metadata.manifest.media_type ${{ github.event.registry_package.package_version.container_metadata.manifest.media_type }}"
          echo "github.event.registry_package.package_version.container_metadata.manifest.config.digest ${{ github.event.registry_package.package_version.container_metadata.manifest.config.digest }}"

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.registry_package.package_version.container_metadata.manifest.media_type }}
          regex: '^.*manifest.list.*$'

      - name: "Combined image"
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          echo "${{ github.event.registry_package.name }}:${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
